#!/bin/sh


mount -t proc /proc /proc
mount -t devpts devpts /dev/pts 
mount -t sysfs sysfs /sys 
mount -t ext2 /dev/sda1 /mnt 

chmod +s /bin/su

ifconfig lo up 

ZEBRA_CONFIG=/mnt/zebra.conf
OSPFD_CONFIG=/mnt/ospf.conf
BABELD_CONFIG=/mnt/babel.conf
BGPD_CONFIG=/mnt/bgpd.conf
RIPD_CONFIG=/mnt/rip.conf
RIPNGD_CONFIG=/mnt/ripng.conf

touch $ZEBRA_CONFIG
touch $OSPFD_CONFIG
touch $BABELD_CONFIG
touch $BGPD_CONFIG
touch $RIPD_CONFIG
touch $RIPNGD_CONFIG

chmod 777 /mnt -R 

hostname test

zebra -d -A 127.0.0.1 -f $ZEBRA_CONFIG
ospfd -d -A 127.0.0.1 -f $OSPFD_CONFIG
bgpd  -d -A 127.0.0.1 -f $BGPD_CONFIG
babeld -d -A 127.0.0.1 -f $BABELD_CONFIG
ripd -d -A 127.0.0.1 -f $RIPD_CONFIG
ripngd -d -A 127.0.0.1 -f $RIPNGD_CONFIG

telnetd
httpd  -h /html
