#!/bin/sh


mount -t proc /proc /proc
mount -t sysfs sysfs /sys 
mount -t ext2 /dev/sda1 /mnt 

ifconfig lo up 
ifconfig eth0 up
ifconfig eth0 172.20.0.2 netmask 255.255.255.0

touch /usr/local/etc/zebra.conf

hostname test

zebra -d -A 127.0.0.1


login

