#!/bin/sh


mount -t proc /proc /proc
mount -t devpts devpts /dev/pts 
mount -t sysfs sysfs /sys 
mount -t ext2 /dev/sda1 /mnt 

chmod +s /bin/su

ifconfig lo up 

ZEBRA_CONFIG=/mnt/zebra.conf
touch $ZEBRA_CONFIG
chmod 777 /mnt -R 

hostname test

zebra -d -A 127.0.0.1 -f $ZEBRA_CONFIG

telnetd
httpd  -h /html
